version: '3.9'

services:
  mongo:
    image: mongo:7
    container_name: mongo-db
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: recruitment_db
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis:7
    container_name: redis-server
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  backend:
    build: ./backend
    container_name: backend-app
    command: sh -c "npm install && npm run dev"
    ports:
      - "4000:4000"
    env_file:
      - ./backend/.env
    depends_on:
      - mongo
      - redis
    volumes:
      - ./backend:/usr/src/app       # monte le code local
      - backend_node_modules:/usr/src/app/node_modules
    restart: unless-stopped

volumes:
  mongo_data:
  redis_data:
  backend_node_modules:
