# Base image
FROM node:20-alpine

# Create app directory
WORKDIR /app

# Copy package files
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy all source code
COPY . .

# Make wait-for-it.sh executable
RUN chmod +x wait-for-it.sh

# Command to wait for DB then start app
CMD ["./wait-for-it.sh", "mongo:27017", "--", "./wait-for-it.sh", "redis:6379", "--", "npm", "run", "dev"]
