# Étape 1 : image Node officielle
FROM node:22

# Étape 2 : dossier de travail à l'intérieur du conteneur
WORKDIR /usr/src/app

# Étape 3 : copier les fichiers package.json et package-lock.json
COPY package*.json ./

# Étape 4 : installer les dépendances
RUN npm install

# Étape 5 : copier le reste du code source
COPY . .

# Étape 6 : exposer le port utilisé par ton serveur
EXPOSE 4000

# Étape 7 : commande de démarrage
CMD ["npm", "run", "dev"]
